name: Build and Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x' # Specify the .NET version here

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore



      # Run tests and collect coverage
      - name: Test with code coverage
        run: dotnet test ./tests/CIDemoTest/CIDemoTest.csproj --collect:"XPlat Code Coverage" --verbosity normal -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura

      # Generate a human-readable coverage report
      - name: Generate coverage report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.9
        with:
          reports: '**/coverage.cobertura.xml'
          targetdir: 'coveragereport'
          reporttypes: 'HtmlInline;Cobertura'

      # Upload the report as an artifact
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coveragereport



      # Statisk kodeanalyse
      - name: Install dotnet format
        run: dotnet tool install -g dotnet-format

      - name: Run code analysis
        run: dotnet format --verify-no-changes --verbosity diagnostic



  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
  
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish
      run: dotnet publish -c Release -o ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: calculator-app
        path: ./publish



    # Nuget Package
    - name: Pack NuGet package
      run: dotnet pack ./src/CalculatorLib/CalculatorLib.csproj -c Release -o ./nupkg

    - name: Upload NuGet package
      uses: actions/upload-artifact@v4
      with:
        name: nuget-package
        path: ./nupkg
